### ISSUE TITLE
PSS issue with status code for submitted payment orders

### ISSUE THREAD

**Issue by svenbiellmann** [swissfintechinnovations/ca-payment#11]
Issue below was already raised in summer 22 during a discussion between SIX and Finnova but so far no definitive answer has been provided.

When submitting an payment order to the Finnova core banking system, this payment order is placed in a queue and, depending on the system load, it may take a few seconds before we know whether the order is fully accepted (ACCP), partially accepted (PART) or rejected (RJCT). If, during this few seconds, the GET /payments/{submissionID}/status endpoint is called, the status RCVD (received) will be returned because the payment order is not yet processed (but received). But this is not in line with the OpenAPI specification of the PSS module where statusCode has to be either ACCP, PART or RJCT.

According to the bLink handbook the FI should respond with an error code. In our opinion an error code is not the right answer because there's no technical error. The payment order is just not yet processed but from a technical point of view everything is fine. Therefore we would suggest to add an additional statusCode RCVD (received) for this situation.

**Comment by simonmeyerm** [comment]
bLink supports adding the payment statusCode "RCVD" as from a processing perspective, "RCVD" would be the starting point before returning the result of the validation.
![Snag_1985da32](https://user-images.githubusercontent.com/115779682/216907438-01cf893e-474f-4c56-b6c6-349982138066.png)

Due to the diagramm above, a Service Provider would return the statusCode "RCVD" until the payment is validated and will return one of the final statusCodes "RJCT, PART, ACCP".
