### ISSUE TITLE
Enhance request of transactions in JSON with date ranges

### ISSUE THREAD

**Issue by simonmeyerm** [swissfintechinnovations/ca-payment#114]
### Contact Details

simon.meyer@six-group.com

### Issue category

Enhancement

### Issue description

Currently, the API requires separate requests for each day of transaction data. This approach leads to excessive API calls and increased server load. In order to improve the API, the requests should be enabled for a specific date range and supported by an appropriate pagination method to limit processing time. 
Although, the query parameter and pagination of the transaction endpoint have been already adjusted, the exact behavior should be defined and open questions clarified. 

### Issue reasoning

This Requirement was brought up within the bLink Multibanking initiative and by several existing and new participants to improve efficiency and performance. Using date-range requests reduces the number of API calls, making interactions more efficient and reducing server load.

### Request

**Date Parameter**
- The query parameters are already adjusted to "dateFrom" and "dateTo". However, the usage of the parameter and sorting of data should be more concise. Therefore, either the description of the parameter or the example value should be adjusted.

**Pagination**
The current pagination used is a combination of cursor-based and offset-limit pagination with links in the response that require the server to process all data.
Cursor-based pagination would be appropriate for the API and the following adjustments could be agreed on:

- Query Parameter "cursor": Define in the description, which attribute should be used as cursor
- Query Parameter "limit": Define a maximum and default number of entries to be returned
- "linksPagination" in Response: Remove the Pagination-Links in the response and add a link to the next page as Response-Header

**Open Questions**

- Currently, transaction list of the current day is requested, by sending the request without a date. Should intraday data be included, when querying date ranges or clearly excluded?
- Status Code 204 would not be required anymore for the transaction endpoint as a list of transactions should always be returned?
- Status Code 202 would still be used, in case data is requested for a booking day, that is not completed yet?

### Proposed change

```oasv2-yaml
Date Parameters
- Change "dateFrom" example value from 2018-04-13 to 01.01.2023
- Change "dateTo" example value from 2018-04-13 to 31.12.2023

Pagination
- Change "cursor" description from "Optional parameter for pagination. An opaque string value used for pagination" 
to 
"Optional parameter for pagination. An opaque string value used for pagination.
Use EntryId as the cursor reference"
- Change "limit" value to max. 50 and default 20
- Add Response-Header "X-Next-Cursor" with description "An opaque string value, or an empty string if there are no more results."
```

### Affected API's

AIS

### Code of Conduct

- [X] I agree to follow this project's Contribution Guidelines

**Comment by svenbiellmann** [comment]
### Meeting Notes 15.8.24

@simonmeyerm elaborates the change request. It was stated that the parameters "date form" and "date to" are in the current specs. But the usage is for single request by setting identical date for both parameters. 

Following details were agreed:
- Only closed days can be requested with date range function. Therefore the transaction with booking status "pending" will not be included. The request for intraday transaction applies analog to the present: no date will be filled in.
- Pagination:
  - The community agreed that there needs to be a consent for equal usage of pagination through all APIs.
  - The pagination shall be curser based (instead of offset paging).
  - The links shall be placed in the header.
  - Action Point: @dkoeni will check the issue and provide feedback.
  - Action Point: @simonmeyerm will then prepare the Pull Request for discussion on next meeting.
- The error codes 202 and 204 may still be accurate and therefore they will be kept as at the present.

**Comment by svenbiellmann** [comment]
### Meeting Notes 26.9.24

The description has been extended and adjusted and cursor setup for pagination is included. The Pull Request will be created after the dependency of #125.

**Comment by svenbiellmann** [comment]
The pull request was merged into the V5 branch. This issue can therefore be closed.
