### ISSUE TITLE
List of Bank Transaction Codes

### ISSUE THREAD

**Issue by juergen-petry** [swissfintechinnovations/ca-payment#13]
It is proposed to provide a static list of values for this entity, comparable to what has been done at the OpenWealth API for the corresponding transaction code.

For payments, SIX has already published a corresponding list in the context of ISO20022

At the bLink side, domain, subdomain and family code is present, but no list is yet defined. This could be addressed by bLink, if it makes sense from bLink's point of view.

**Comment by simonmeyerm** [comment]
Generally, the codes could be added as an enum to the respective domain-, family- and subFamilyCodes. 
However, as the codes change on a regular basis (2020-2021 -> 1 change / 2021-2022 -> 5 changes), the APIs would have to be adjusted with a breaking change. 

Due to the fact, that the adjustment would make the API less flexibel and results to future breaking changes without an essential benefit, the suggestion of bLink would be to not add the respective codes.

**Comment by juergen-petry** [comment]
Topic suggested to be dropped.
